---
- hosts: default
  become: true
  pre_tasks:
    - name: check for virtualization extensions in cpuinfo
      shell: egrep '(vmx|svm)' /proc/cpuinfo
    - name: update APT cache
      apt:
        update_cache: yes
    - name: perform system upgrade
      package:
        name: '*'
        state: latest
        force_apt_get: yes
  tasks:
    - include: xen.yml
      when: not source

    - include: xen_source.yml
      when: source
